build application
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
yarn run v1.22.21
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
yarn run v1.22.21
$ tsc && vite build
src/main.ts:517:19 - error TS6133: 'index' is declared but its value is never read.

517     loopClusters((index, column, row, cluster) => {
                      ~~~~~

src/main.ts:517:39 - error TS6133: 'cluster' is declared but its value is never read.

517     loopClusters((index, column, row, cluster) => {
                                          ~~~~~~~

src/main.ts:638:20 - error TS6133: 'e' is declared but its value is never read.

638 function onMouseUp(e: MouseEvent) {
                       ~

src/main.ts:642:21 - error TS6133: 'e' is declared but its value is never read.

642 function onMouseOut(e: MouseEvent) {
                        ~

Found 4 errors in the same file, starting at: src/main.ts:517

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\kushal\src\myhtml\matchthree\matchthree> yarn build
yarn run v1.22.21
$ tsc && vite build
vite v5.4.8 building for production...
✓ 3 modules transformed.
docs/index.html                0.33 kB │ gzip: 0.25 kB
docs/assets/index-B_l4UiSx.js  8.17 kB │ gzip: 2.97 kB
✓ built in 368ms
Done in 1.64s.
PS C:\Users\kushal\src\myhtml\matchthree\matchthree>